"""Add media_type to AboutImage model

Revision ID: 0eecf507f274
Revises: 293e0419475e
Create Date: 2025-10-18 12:24:58.641343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eecf507f274'
down_revision = '293e0419475e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=False, server_default='image'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_images', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
