"""Add service_id to bookings

Revision ID: 475060cbad9e
Revises: 
Create Date: 2025-08-27 19:47:33.808343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475060cbad9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_booking_service_id', 'services', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_service_id', type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
